/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql1;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author hugo
 */
public class V extends javax.swing.JFrame {
    CBD cbd =new CBD();
    ImageIcon ajuste= null,icon;
    File archI;
    /**
     * Creates new form V
     */
    public V() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTMostrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BTBuscarImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 200));

        BTMostrar.setText("mostrar");
        BTMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMostrarActionPerformed(evt);
            }
        });

        jButton1.setText("salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BTBuscarImagen.setText("Buscar imagen");
        BTBuscarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBuscarImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(BTMostrar)
                .addGap(103, 103, 103)
                .addComponent(BTBuscarImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTMostrar)
                    .addComponent(jButton1)
                    .addComponent(BTBuscarImagen))
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMostrarActionPerformed
        try {
            Mostrar();
        } catch (IOException ex) {
            Logger.getLogger(V.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTMostrarActionPerformed

    private void BTBuscarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBuscarImagenActionPerformed
          JFileChooser fs = new JFileChooser (new File("/home/hugo/Imatges"));
        fs.setDialogTitle("Save a file");
        //crear opciones de tipo filtro
        
        fs.setFileFilter(new  ArchivosTipoFiltro(".jpeg","archivo .jpeg"));
        fs.setFileFilter(new  ArchivosTipoFiltro(".jpg","archivo .jpg"));
        fs.setFileFilter(new  ArchivosTipoFiltro(".png","archivo .png"));
        fs.setFileFilter(new  ArchivosTipoFiltro(".gif","archivo .gif"));
        int resultado=fs.showSaveDialog(null);
        if (resultado== JFileChooser.APPROVE_OPTION) 
        {
            
            this.archI=fs.getSelectedFile();
            ImageIcon ipa = new ImageIcon(archI.toString());
            Icon dipa = new ImageIcon(ipa.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
            this.jLabel1.setText(null);
            this.jLabel1.setIcon(dipa);
            
            
        }    
    }//GEN-LAST:event_BTBuscarImagenActionPerformed

    public void Mostrar() throws IOException       
    {
         cbd.consultaImagene("hugo");
         ajuste= new ImageIcon(cbd.img.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_SMOOTH)); 
         jLabel1.setText("");      
         jLabel1.setIcon(ajuste);
         jLabel1.updateUI();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTBuscarImagen;
    private javax.swing.JButton BTMostrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
